includes:
- ^/etc
- ^/usr
- ^/usr/bin
- ^/usr/bin/c++-{{.Values.version}}
- ^/usr/bin/cpp-{{.Values.version}}
- ^/usr/bin/g++-{{.Values.version}}
- ^/usr/bin/gcc-{{.Values.version}}
- ^/usr/bin/gccgo-{{.Values.version}}
- ^/usr/bin/gcov-{{.Values.version}}
- ^/usr/bin/gfortran-{{.Values.version}}
- ^/usr/bin/x86_64-pc-linux-gnu-c++-{{.Values.version}}
- ^/usr/bin/x86_64-pc-linux-gnu-cpp-{{.Values.version}}
- ^/usr/bin/x86_64-pc-linux-gnu-g++-{{.Values.version}}
- ^/usr/bin/x86_64-pc-linux-gnu-gcc-{{.Values.version}}
- ^/usr/bin/x86_64-pc-linux-gnu-gccgo-{{.Values.version}}
- ^/usr/bin/x86_64-pc-linux-gnu-gcov-{{.Values.version}}
- ^/usr/bin/x86_64-pc-linux-gnu-gfortran-{{.Values.version}}
- ^/usr/lib
- ^/usr/lib/gcc
- ^/usr/lib/gcc/x86_64-pc-linux-gnu
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}.*
- ^/usr/lib/go
- ^/usr/lib/go/{{.Values.version}}.*
- ^/usr/lib64
- ^/usr/lib64/go
- ^/usr/lib64/go/{{.Values.version}}.*
- ^/usr/libexec
- ^/usr/libexec/gcc
- ^/usr/libexec/gcc/x86_64-pc-linux-gnu
- ^/usr/libexec/gcc/x86_64-pc-linux-gnu/{{.Values.version}}.*
- ^/usr/share
- ^/usr/share/gcc-data
- ^/usr/share/gcc-data/x86_64-pc-linux-gnu
- ^/usr/share/gcc-data/x86_64-pc-linux-gnu/{{.Values.version}}.*
- ^/usr/share/gdb
- ^/usr/share/gdb/auto-load
- ^/usr/share/gdb/auto-load/usr
- ^/usr/share/gdb/auto-load/usr/lib
- ^/usr/share/gdb/auto-load/usr/lib/gcc
- ^/usr/share/gdb/auto-load/usr/lib/gcc/x86_64-pc-linux-gnu
- ^/usr/share/gdb/auto-load/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}.*
- ^/usr/x86_64-pc-linux-gnu
- ^/usr/x86_64-pc-linux-gnu/gcc-bin
- ^/usr/x86_64-pc-linux-gnu/gcc-bin/{{.Values.version}}.*
unpack: true
requires:
- name: system-x
  version: ">=0"
  category: layers