steps:
- curl https://get.mocaccino.org/luet/get_luet_root.sh | sh
- luet install repository/mocaccino-extra-stable system/luet-extensions-live
- luet install dev-util/pkgs-checker-minimal utils/jq
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} ${CLANG_10_PKGS}
env:
- LUET_NOLOCK=true
- LUET_PORTAGE_CACHE_PACKAGES=/var/cache/binpkgs/
- LUET_YES=true
package_dir: /{{ .Values.name }}
requires:
- name: clang-10
  version: '>=0'
  category: layers
includes:
- ^/usr/include/.*
- ^/usr/lib/clang/10.0.1/include/.*
- ^/usr/lib/llvm/10/bin
- ^/usr/lib/llvm/10/bin/.*
- ^/usr/lib/llvm/10/include.*
- ^/usr/lib/llvm/10/lib/cmake.*
- ^/usr/lib/llvm/10/libexec.*
