includes:
- /usr$
- /usr/bin$
- /usr/bin/cc.*
- /usr/bin/c\+\+.*
- /usr/bin/cpp.*
- /usr/bin/g\+\+.*
- /usr/bin/gcc.*
- /usr/bin/gccgo.*
- /usr/bin/gcov.*
- /usr/bin/gfortran.*
- /usr/bin/go-.*
- /usr/bin/gofmt-.*
- /usr/bin/x86_64-pc-linux-gnu-.*
- /usr/bin/c\+\+.*
- /usr/lib$
- /usr/lib/gcc$
- /usr/lib/gcc/x86_64-pc-linux-gnu$
- /usr/lib/gcc/x86_64-pc-linux-gnu/{{( index .Values.labels "gcc.version" )}}.*
- /usr/lib/go$
- /usr/lib/go/{{( index .Values.labels "gcc.version" )}}.*
- /usr/lib64$
- /usr/lib64/go$
- /usr/lib64/go/{{( index .Values.labels "gcc.version" )}}.*
- /usr/libexec$
- /usr/libexec/gcc$
- /usr/libexec/gcc/x86_64-pc-linux-gnu$
- /usr/libexec/gcc/x86_64-pc-linux-gnu/{{( index .Values.labels "gcc.version" )}}.*
- /usr/share$
- /usr/share/gcc-data$
- /usr/share/gcc-data/x86_64-pc-linux-gnu$
- /usr/share/gcc-data/x86_64-pc-linux-gnu/{{( index .Values.labels "gcc.version" )}}.*
- /usr/share/gdb$
- /usr/share/gdb/auto-load$
- /usr/share/gdb/auto-load/usr$
- /usr/share/gdb/auto-load/usr/lib$
- /usr/share/gdb/auto-load/usr/lib/gcc$
- /usr/share/gdb/auto-load/usr/lib/gcc/x86_64-pc-linux-gnu$
- /usr/share/gdb/auto-load/usr/lib/gcc/x86_64-pc-linux-gnu/{{( index .Values.labels "gcc.version" )}}.*
- /usr/x86_64-pc-linux-gnu$
- /usr/x86_64-pc-linux-gnu/gcc-bin$
- /usr/x86_64-pc-linux-gnu/gcc-bin/{{( index .Values.labels "gcc.version" )}}.*
excludes:
- ^/usr/lib/llvm/.*/lib.*/libLLVM.*.so
- ^/usr/lib/debug/usr/lib/gcc/x86_64-pc-linux-gnu/{{( index .Values.labels "gcc.version" )}}/.*
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{( index .Values.labels "gcc.version" )}}/32/crtbegin.o
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{( index .Values.labels "gcc.version" )}}/32/crtbeginS.o
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{( index .Values.labels "gcc.version" )}}/32/crtbeginT.o
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{( index .Values.labels "gcc.version" )}}/32/crtend.o
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{( index .Values.labels "gcc.version" )}}/32/crtendS.o
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{( index .Values.labels "gcc.version" )}}/32/crtfastmath.o
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{( index .Values.labels "gcc.version" )}}/32/crtprec32.o
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{( index .Values.labels "gcc.version" )}}/32/crtprec64.o
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{( index .Values.labels "gcc.version" )}}/32/crtprec80.o
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{( index .Values.labels "gcc.version" )}}/32/finclude/ieee_arithmetic.mod
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{( index .Values.labels "gcc.version" )}}/32/finclude/ieee_exceptions.mod
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{( index .Values.labels "gcc.version" )}}/32/finclude/ieee_features.mod
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{( index .Values.labels "gcc.version" )}}/32/libatomic.*
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{( index .Values.labels "gcc.version" )}}/32/libgcc_s.so
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{( index .Values.labels "gcc.version" )}}/32/libgcc_s.so.1
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{( index .Values.labels "gcc.version" )}}/32/libgfortran.*
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{( index .Values.labels "gcc.version" )}}/32/libgomp.*
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{( index .Values.labels "gcc.version" )}}/32/libobjc.*
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{( index .Values.labels "gcc.version" )}}/32/libquadmath.*
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{( index .Values.labels "gcc.version" )}}/32/libstdc.*
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{( index .Values.labels "gcc.version" )}}/32/vtv_.*
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{( index .Values.labels "gcc.version" )}}/crt.*
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{( index .Values.labels "gcc.version" )}}/finclude/ieee_arithmetic.mod
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{( index .Values.labels "gcc.version" )}}/finclude/ieee_exceptions.mod
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{( index .Values.labels "gcc.version" )}}/finclude/ieee_features.mod
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{( index .Values.labels "gcc.version" )}}/libatomic.*
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{( index .Values.labels "gcc.version" )}}/libgcc_s.*
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{( index .Values.labels "gcc.version" )}}/libgfortran.*
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{( index .Values.labels "gcc.version" )}}/libgomp.*
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{( index .Values.labels "gcc.version" )}}/libobjc.*
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{( index .Values.labels "gcc.version" )}}/libquadmath.*
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{( index .Values.labels "gcc.version" )}}/libstdc.*
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{( index .Values.labels "gcc.version" )}}/vtv_.*
- ^/usr/share/gcc-data/x86_64-pc-linux-gnu/{{( index .Values.labels "gcc.version" )}}/info/libgomp.info
- ^/usr/share/gcc-data/x86_64-pc-linux-gnu/{{( index .Values.labels "gcc.version" )}}/info/libquadmath.info
- ^/usr/share/gcc-data/x86_64-pc-linux-gnu/{{( index .Values.labels "gcc.version" )}}/locale/de/LC_MESSAGES
- ^/usr/share/gcc-data/x86_64-pc-linux-gnu/{{( index .Values.labels "gcc.version" )}}/locale/de/LC_MESSAGES/.*
- ^/usr/share/gcc-data/x86_64-pc-linux-gnu/{{( index .Values.labels "gcc.version" )}}/locale/fr/LC_MESSAGES/.*
unpack: true
requires:
- name: system-core
  version: ">=0"
  category: layers
