requires:
# TODO: on install it manually with pip it's needed npm for sphinx funtoo theme.
- category: "net-libs"
  name: "nodejs"
  version: ">=0"
package_dir: /gentoo
prelude:
- rm -rf /var/db/repos/gentoo
- git clone {{ ( index .Values.labels "portage.git.url" ) }} /var/db/repos/gentoo
- cd /var/db/repos/gentoo && git checkout $PORTAGE_HASH
- git clone {{ ( index .Values.labels "funtoo.metatools.git.url" ) }} /funtoo-metatools
# Fix temporary until setup.py will contains this dep
- emerge pymongo
- cd /funtoo-metatools && python setup.py install
# TODO: replace it when we could supply an external config file.
- cp reposcan /funtoo-metatools/bin/
env:
# TODO: to replace with the patch about set target dir.
- JSON_OUTPUT=/root/repo_tmp/tmp/kit_cache/gentoo-master
steps:
- source /etc/profile && cd /funtoo-metatools && PYTHONPATH=. ./bin/reposcan
- mkdir /gentoo/etc/mocaccino/reposcan/ -p && cp ${JSON_OUTPUT} /gentoo/etc/mocaccino/reposcan/
