requires:
- category: "development"
  name: "mocaccino-overlay-core"
  version: ">=0"
unpack: true
env:
- FEATURES="-sandbox -usersandbox -ipc-sandbox -pid-sandbox -network-sandbox"
- JOBS=7
prelude:
- eval 'emerge --unmerge dev-lang/python:3.8 dev-lang/python:3.9 dev-lang/python:2.7 dev-lang/ruby:2.5 || true'
- emerge dev-perl/XML-Parser -j $JOBS
steps:
- emerge -uDNv --with-bdeps=y --backtrack=100 --autounmask-keep-masks=y @world -j $JOBS
- emerge sys-apps/systemd
- perl-cleaner --all

excludes:
- ^/etc/shadow
- ^/etc/os-release
- ^/etc/gshadow
- ^/etc/group
- ^/etc/hostname
- ^/etc/hosts
- ^/etc/machine-id
- ^/etc/fstab
- ^/etc/passwd
- ^/etc/machineid
- ^/etc/resolv.conf
- ^/var/db/repos
- ^/var/db/pkg
- ^/var/lib/portage
- ^/var/cache/distfiles
- ^/var/log
- ^/var/cache/edb
- ^/usr/portage
- ^/sys
- ^/proc
- ^/luetbuild

# Python test
- ^/usr/lib/python3.7/test/

# Exclude xmlto available on layers/system-x
- ^/usr/share/xmlto
- ^/usr/share/man/man1/xmlto.1.bz2
- ^/usr/share/man/man1/xmlif.1.bz2
- ^/usr/bin/xmlto
- ^/usr/bin/xmlif
- ^/usr/share/doc/xmlto.*

# Exclude dbus rebuild on layers/system-x
- ^/usr/lib/pkgconfig/dbus-1.pc
- ^/usr/lib/dbus-1.0/include/dbus/.*
- ^/usr/lib/libdbus.*
- ^/usr/lib/sysusers.d/dbus.conf
- ^/usr/lib/tmpfiles.d/dbus.conf
- ^/usr/lib/systemd/user/dbus.*
- ^/usr/lib/systemd/user/sockets.target.wants/dbus.socket
- ^/usr/include/dbus-1.0/.*
- ^/usr/lib64/dbus-1.0/include/dbus/.*
- ^/usr/lib64/libdbus.*
- ^/usr/lib64/cmake/DBus1/.*
- ^/usr/bin/dbus-.*
- ^/usr/share/dbus-1/.*
- ^/usr/share/doc/dbus-.*
- ^/usr/share/xml/dbus-1.*
- ^/usr/share/man/man1/dbus.*
- ^/usr/libexec/dbus-daemon-launch-helper
- ^/etc/dbus-1/.*
- ^/etc/X11/xinit/xinitrc.d/80-dbus
- ^/lib/systemd/system/dbus.*
- ^/lib/systemd/system/sockets.target.wants/dbus.*

# Exclude pinentry rebuild on layers/system-x
- ^/usr/bin/pinentry*
- ^/usr/share/info/pinentry.*
- ^/usr/share/doc/pinentry-base.*

# We don't need openrc
- ^/etc/init.d/.*

# GCC split
- ^/etc/env.d/04gcc-x86_64-pc-linux-gnu
- ^/etc/ld.so.conf.d/05gcc-x86_64-pc-linux-gnu.conf
- ^/etc/env.d/gcc.*
- ^/usr/lib/debug/usr/lib/gcc.*
- ^/usr/lib/gcc/x86_64-pc-linux-gnu.*
- ^/usr/share/gcc-data/x86_64-pc-linux-gnu.*
- ^/usr/bin/c\+\+.*
- ^/usr/bin/cc$
- ^/usr/bin/cpp.*
- ^/usr/bin/g\+\+.*
- ^/usr/bin/gcc.*
- ^/usr/bin/gccgo.*
- ^/usr/bin/go-.*
- ^/usr/bin/gofmt-.*
- ^/usr/bin/gcov.*
- ^/usr/bin/gfortran.*
- ^/usr/bin/x86_64-pc-linux-gnu-.*
- ^/usr/lib/gcc/x86_64-pc-linux-gnu.*
- ^/usr/lib/go.*
- ^/usr/lib64/go.*
- ^/usr/libexec/gcc.*
- ^/usr/share/gcc-data.*
- ^/usr/x86_64-pc-linux-gnu/gcc-bin.*
- ^/usr/lib/gcc
- ^/usr/lib/llvm.*
- ^/usr/lib/clang.*
- ^/etc/lvm.*

# devel
- ^/usr/include
