requires:
- category: "development"
  name: "mocaccino-overlay-core"
  version: ">=0"
unpack: true
env:
- FEATURES="-sandbox -usersandbox -ipc-sandbox -pid-sandbox -network-sandbox"
- JOBS=7
prelude:
- eval 'emerge --unmerge dev-lang/python:3.8 dev-lang/python:3.9 dev-lang/python:2.7 dev-lang/ruby:2.5 || true'
- emerge dev-perl/XML-Parser -j $JOBS
steps:
- emerge -uDNv --with-bdeps=y --backtrack=100 --autounmask-keep-masks=y @world -j $JOBS
- emerge sys-apps/systemd
- perl-cleaner --all

excludes:
- ^/etc/shadow
- ^/etc/os-release
- ^/etc/gshadow
- ^/etc/group
- ^/etc/hostname
- ^/etc/hosts
- ^/etc/machine-id
- ^/etc/fstab
- ^/etc/passwd
- ^/etc/machineid
- ^/etc/resolv.conf
- ^/var/db/repos
- ^/var/db/pkg
- ^/var/lib/portage
- ^/var/cache/distfiles
- ^/var/log
- ^/var/cache/edb
- ^/usr/portage
- ^/sys
- ^/proc
- ^/luetbuild

# Python test
- ^/usr/lib/python3.7/test/

# Exclude xmlto available on layers/system-x
- ^/usr/share/xmlto
- ^/usr/share/man/man1/xmlto.1.bz2
- ^/usr/share/man/man1/xmlif.1.bz2
- ^/usr/bin/xmlto
- ^/usr/bin/xmlif
- ^/usr/share/doc/xmlto.*

# Exclude dbus rebuild on layers/system-x
- ^/usr/lib/pkgconfig/dbus-1.pc
- ^/usr/lib/dbus-1.0/include/dbus/.*
- ^/usr/lib/libdbus.*
- ^/usr/lib/sysusers.d/dbus.conf
- ^/usr/lib/tmpfiles.d/dbus.conf
- ^/usr/lib/systemd/user/dbus.*
- ^/usr/lib/systemd/user/sockets.target.wants/dbus.socket
- ^/usr/include/dbus-1.0/.*
- ^/usr/lib64/dbus-1.0/include/dbus/.*
- ^/usr/lib64/libdbus.*
- ^/usr/lib64/cmake/DBus1/.*
- ^/usr/bin/dbus-.*
- ^/usr/share/dbus-1/.*
- ^/usr/share/doc/dbus-.*
- ^/usr/share/xml/dbus-1.*
- ^/usr/share/man/man1/dbus.*
- ^/usr/libexec/dbus-daemon-launch-helper
- ^/etc/dbus-1/.*
- ^/etc/X11/xinit/xinitrc.d/80-dbus
- ^/lib/systemd/system/dbus.*
- ^/lib/systemd/system/sockets.target.wants/dbus.*

# Exclude pinentry rebuild on layers/system-x
- ^/usr/bin/pinentry*
- ^/usr/share/info/pinentry.*
- ^/usr/share/doc/pinentry-base.*

# Exclude systemd rebuild on layers/system-x
- ^/usr/share/factory/etc/pam.d/system-auth
- ^/usr/share/factory/etc/pam.d/other
- ^/usr/share/factory/etc/nsswitch.conf
- ^/usr/share/dbus-1/system.d/org.freedesktop.*
- ^/usr/share/dbus-1/system-services/org.freedesktop.*
- ^/usr/share/polkit-1/actions/org.freedesktop.*
- ^/usr/share/polkit-1/rules.d/systemd-networkd.rules
- ^/usr/share/pkgconfig/systemd.pc
- ^/usr/share/pkgconfig/udev.pc
- ^/usr/share/bash-completion/completions/busctl
- ^/usr/share/bash-completion/completions/journalctl
- ^/usr/share/bash-completion/completions/systemd-.*
- ^/usr/share/bash-completion/completions/udevadm
- ^/usr/share/bash-completion/completions/kernel-install
- ^/usr/share/bash-completion/completions/systemctl
- ^/usr/share/bash-completion/completions/bootctl
- ^/usr/share/bash-completion/completions/coredumpctl
- ^/usr/share/bash-completion/completions/hostnamectl
- ^/usr/share/bash-completion/completions/localectl
- ^/usr/share/bash-completion/completions/loginctl
- ^/usr/share/bash-completion/completions/machinectl
- ^/usr/share/bash-completion/completions/networkctl
- ^/usr/share/bash-completion/completions/portablectl
- ^/usr/share/bash-completion/completions/resolvectl
- ^/usr/share/bash-completion/completions/systemd-resolve
- ^/usr/share/bash-completion/completions/timedatectl
- ^/usr/share/zsh/site-functions/_busctl
- ^/usr/share/zsh/site-functions/_journalctl
- ^/usr/share/zsh/site-functions/_systemd-.*
- ^/usr/share/zsh/site-functions/_udevadm
- ^/usr/share/zsh/site-functions/_kernel-install
- ^/usr/share/zsh/site-functions/_sd_.*
- ^/usr/share/zsh/site-functions/_systemctl
- ^/usr/share/zsh/site-functions/_.*ctl
- ^/usr/share/zsh/site-functions/_systemd-.*
- ^/usr/share/zsh/site-functions/_timedatectl
- /usr/share/doc/systemd-.*
- .*systemd.mo$
- ^/usr/share/man/man5/coredump.conf.d.5
- ^/usr/share/man/man5/systemd.negative.5
- ^/usr/share/man/man5/systemd.positive.5
- ^/usr/share/man/man5/journald.conf.d.5
- ^/usr/share/man/man5/logind.conf.d.5
- ^/usr/share/man/man5/networkd.conf.d.5
- ^/usr/share/man/man5/resolved.conf.d.5
- ^/usr/share/man/man5/sleep.conf.d.5
- ^/usr/share/man/man5/system.conf.d.5
- ^/usr/share/man/man5/systemd-user.conf.5
- ^/usr/share/man/man5/user.conf.d.5
- ^/usr/share/man/man5/timesyncd.conf.d.5
- ^/usr/share/man/man5/user-runtime-dir@.service.5
- ^/usr/share/man/man5/crypttab.5.bz2
- ^/usr/share/man/man5/binfmt.d.5.bz2
- ^/usr/share/man/man5/coredump.conf.5.bz2
- ^/usr/share/man/man5/dnssec-trust-anchors.d.5.bz2
- ^/usr/share/man/man5/environment.d.5.bz2
- ^/usr/share/man/man5/hostname.5.bz2
- ^/usr/share/man/man5/journald.conf.5.bz2
- ^/usr/share/man/man5/loader.conf.5.bz2
- ^/usr/share/man/man5/locale.conf.5.bz2
- ^/usr/share/man/man5/localtime.5.bz2
- ^/usr/share/man/man5/logind.conf.5.bz2
- ^/usr/share/man/man5/machine-id.5.bz2
- ^/usr/share/man/man5/machine-info.5.bz2
- ^/usr/share/man/man5/networkd.conf.5.bz2
- ^/usr/share/man/man5/modules-load.d.5.bz2
- ^/usr/share/man/man5/os-release.5.bz2
- ^/usr/share/man/man5/sysctl.d.5.bz2
- ^/usr/share/man/man5/resolved.conf.5.bz2
- ^/usr/share/man/man5/systemd-sleep.conf.5.bz2
- ^/usr/share/man/man5/systemd-system.conf.5.bz2
- ^/usr/share/man/man5/systemd.link.5.bz2
- ^/usr/share/man/man5/systemd.dnssd.5.bz2
- ^/usr/share/man/man5/systemd.device.5.bz2
- ^/usr/share/man/man5/systemd.automount.5.bz2
- ^/usr/share/man/man5/systemd.kill.5.bz2
- ^/usr/share/man/man5/systemd.exec.5.bz2
- ^/usr/share/man/man5/systemd.mount.5.bz2
- ^/usr/share/man/man5/systemd.netdev.5.bz2
- ^/usr/share/man/man5/systemd.network.5.bz2
- ^/usr/share/man/man5/systemd.preset.5.bz2
- ^/usr/share/man/man5/systemd.nspawn.5.bz2
- ^/usr/share/man/man5/systemd.resource-control.5.bz2
- ^/usr/share/man/man5/systemd.path.5.bz2
- ^/usr/share/man/man5/systemd.scope.5.bz2
- ^/usr/share/man/man5/systemd.service.5.bz2
- ^/usr/share/man/man5/systemd.slice.5.bz2
- ^/usr/share/man/man5/systemd.socket.5.bz2
- ^/usr/share/man/man5/systemd.swap.5.bz2
- ^/usr/share/man/man5/systemd.target.5.bz2
- ^/usr/share/man/man5/systemd.unit.5.bz2
- ^/usr/share/man/man5/systemd.timer.5.bz2
- ^/usr/share/man/man5/sysusers.d.5.bz2
- ^/usr/share/man/man5/timesyncd.conf.5.bz2
- ^/usr/share/man/man5/udev.conf.5.bz2
- ^/usr/share/man/man5/tmpfiles.d.5.bz2
- ^/usr/share/man/man5/vconsole.conf.5.bz2
- ^/usr/share/man/man5/user@.service.5.bz2
- ^/usr/share/man/man1/resolvconf.1
- ^/usr/share/man/man1/systemd-firstboot.service.1
- ^/usr/share/man/man1/systemd-umount.1
- ^/usr/share/man/man1/init.1
- ^/usr/share/man/man1/bootctl.1.bz2
- ^/usr/share/man/man1/busctl.1.bz2
- ^/usr/share/man/man1/coredumpctl.1.bz2
- ^/usr/share/man/man1/hostnamectl.1.bz2
- ^/usr/share/man/man1/journalctl.1.bz2
- ^/usr/share/man/man1/localectl.1.bz2
- ^/usr/share/man/man1/loginctl.1.bz2
- ^/usr/share/man/man1/machinectl.1.bz2
- ^/usr/share/man/man1/resolvectl.1.bz2
- ^/usr/share/man/man1/portablectl.1.bz2
- ^/usr/share/man/man1/systemctl.1.bz2
- ^/usr/share/man/man1/networkctl.1.bz2
- ^/usr/share/man/man1/systemd-analyze.1.bz2
- ^/usr/share/man/man1/systemd-ask-password.1.bz2
- ^/usr/share/man/man1/systemd-cat.1.bz2
- ^/usr/share/man/man1/systemd-delta.1.bz2
- ^/usr/share/man/man1/systemd-detect-virt.1.bz2
- ^/usr/share/man/man1/systemd-escape.1.bz2
- ^/usr/share/man/man1/systemd-cgtop.1.bz2
- ^/usr/share/man/man1/systemd-cgls.1.bz2
- ^/usr/share/man/man1/systemd-firstboot.1.bz2
- ^/usr/share/man/man1/systemd-id128.1.bz2
- ^/usr/share/man/man1/systemd-inhibit.1.bz2
- ^/usr/share/man/man1/systemd-path.1.bz2
- ^/usr/share/man/man1/systemd-notify.1.bz2
- ^/usr/share/man/man1/systemd-machine-id-setup.1.bz2
- ^/usr/share/man/man1/systemd-mount.1.bz2
- ^/usr/share/man/man1/systemd-run.1.bz2
- ^/usr/share/man/man1/systemd-nspawn.1.bz2
- ^/usr/share/man/man1/systemd-socket-activate.1.bz2
- ^/usr/share/man/man1/systemd-tty-ask-password-agent.1.bz2
- ^/usr/share/man/man1/timedatectl.1.bz2
- ^/usr/share/man/man1/systemd.1.bz2
- ^/usr/share/man/man7/sd-boot.7
- ^/usr/share/man/man7/bootup.7.bz2
- ^/usr/share/man/man7/file-hierarchy.7.bz2
- ^/usr/share/man/man7/daemon.7.bz2
- ^/usr/share/man/man7/hwdb.7.bz2
- ^/usr/share/man/man7/kernel-command-line.7.bz2
- ^/usr/share/man/man7/systemd-boot.7.bz2
- ^/usr/share/man/man7/systemd.environment-generator.7.bz2
- ^/usr/share/man/man7/systemd.generator.7.bz2
- ^/usr/share/man/man7/systemd.syntax.7.bz2
- ^/usr/share/man/man7/systemd.time.7.bz2
- ^/usr/share/man/man7/systemd.journal-fields.7.bz2
- ^/usr/share/man/man7/systemd.special.7.bz2
- ^/usr/share/man/man7/systemd.offline-updates.7.bz2
- ^/usr/share/man/man7/systemd.directives.7.bz2
- ^/usr/share/man/man7/udev.7.bz2
- ^/usr/share/man/man7/systemd.index.7.bz2
- ^/usr/share/man/man8/poweroff.8
- ^/usr/share/man/man8/reboot.8
- ^/usr/share/man/man8/libnss_myhostname.so.2.8
- ^/usr/share/man/man8/libnss_mymachines.so.2.8
- ^/usr/share/man/man8/libnss_resolve.so.2.8
- ^/usr/share/man/man8/libnss_systemd.so.2.8
- ^/usr/share/man/man8/systemd-ask-password-console.path.8
- ^/usr/share/man/man8/systemd-ask-password-wall.path.8
- ^/usr/share/man/man8/systemd-ask-password-wall.service.8
- ^/usr/share/man/man8/systemd-backlight.8
- ^/usr/share/man/man8/systemd-binfmt.8
- ^/usr/share/man/man8/systemd-coredump.socket.8
- ^/usr/share/man/man8/systemd-coredump@.service.8
- ^/usr/share/man/man8/systemd-cryptsetup.8
- ^/usr/share/man/man8/30-systemd-environment-d-generator.8
- ^/usr/share/man/man8/systemd-fsck.8
- ^/usr/share/man/man8/systemd-fsck-root.service.8
- ^/usr/share/man/man8/systemd-kexec.service.8
- ^/usr/share/man/man8/systemd-poweroff.service.8
- ^/usr/share/man/man8/systemd-reboot.service.8
- ^/usr/share/man/man8/systemd-shutdown.8
- ^/usr/share/man/man8/systemd-hibernate-resume.8
- ^/usr/share/man/man8/systemd-hostnamed.8
- ^/usr/share/man/man8/systemd-initctl.8
- ^/usr/share/man/man8/systemd-initctl.socket.8
- ^/usr/share/man/man8/systemd-journald.8
- ^/usr/share/man/man8/systemd-journald-audit.socket.8
- ^/usr/share/man/man8/systemd-journald-dev-log.socket.8
- ^/usr/share/man/man8/systemd-journald.socket.8
- ^/usr/share/man/man8/systemd-localed.8
- ^/usr/share/man/man8/systemd-logind.8
- ^/usr/share/man/man8/systemd-machined.8
- ^/usr/share/man/man8/systemd-growfs.8
- ^/usr/share/man/man8/systemd-growfs@.service.8
- ^/usr/share/man/man8/systemd-makefs.8
- ^/usr/share/man/man8/systemd-makeswap@.service.8
- ^/usr/share/man/man8/systemd-modules-load.8
- ^/usr/share/man/man8/systemd-networkd-wait-online.8
- ^/usr/share/man/man8/systemd-networkd.8
- ^/usr/share/man/man8/systemd-portabled.8
- ^/usr/share/man/man8/systemd-quotacheck.8
- ^/usr/share/man/man8/systemd-random-seed.8
- ^/usr/share/man/man8/systemd-remount-fs.8
- ^/usr/share/man/man8/systemd-resolved.8
- ^/usr/share/man/man8/systemd-rfkill.8
- ^/usr/share/man/man8/systemd-rfkill.socket.8
- ^/usr/share/man/man8/systemd-hibernate.service.8
- ^/usr/share/man/man8/systemd-hybrid-sleep.service.8
- ^/usr/share/man/man8/systemd-sleep.8
- ^/usr/share/man/man8/systemd-suspend-then-hibernate.service.8
- ^/usr/share/man/man8/systemd-sysctl.8
- ^/usr/share/man/man8/systemd-sysusers.service.8
- ^/usr/share/man/man8/systemd-time-wait-sync.8
- ^/usr/share/man/man8/systemd-timedated.8
- ^/usr/share/man/man8/systemd-timesyncd.8
- ^/usr/share/man/man8/systemd-tmpfiles-clean.service.8
- ^/usr/share/man/man8/systemd-tmpfiles-clean.timer.8
- ^/usr/share/man/man8/systemd-tmpfiles-setup-dev.service.8
- ^/usr/share/man/man8/systemd-tmpfiles-setup.service.8
- ^/usr/share/man/man8/systemd-udevd.8
- ^/usr/share/man/man8/systemd-udevd-control.socket.8
- ^/usr/share/man/man8/systemd-udevd-kernel.socket.8
- ^/usr/share/man/man8/systemd-update-done.8
- ^/usr/share/man/man8/systemd-update-utmp.8
- ^/usr/share/man/man8/systemd-update-utmp-runlevel.service.8
- ^/usr/share/man/man8/systemd-user-sessions.8
- ^/usr/share/man/man8/systemd-vconsole-setup.8
- ^/usr/share/man/man8/systemd-veritysetup.8
- ^/usr/share/man/man8/systemd-volatile-root.8
- ^/usr/share/man/man8/kernel-install.8.bz2
- ^/usr/share/man/man8/halt.8.bz2
- ^/usr/share/man/man8/nss-myhostname.8.bz2
- ^/usr/share/man/man8/nss-mymachines.8.bz2
- ^/usr/share/man/man8/nss-resolve.8.bz2
- ^/usr/share/man/man8/nss-systemd.8.bz2
- ^/usr/share/man/man8/runlevel.8.bz2
- ^/usr/share/man/man8/pam_systemd.8.bz2
- ^/usr/share/man/man8/shutdown.8.bz2
- ^/usr/share/man/man8/systemd-ask-password-console.service.8.bz2
- ^/usr/share/man/man8/systemd-backlight@.service.8.bz2
- ^/usr/share/man/man8/systemd-binfmt.service.8.bz2
- ^/usr/share/man/man8/systemd-bless-boot-generator.8.bz2
- ^/usr/share/man/man8/systemd-bless-boot.service.8.bz2
- ^/usr/share/man/man8/systemd-boot-check-no-failures.service.8.bz2
- ^/usr/share/man/man8/systemd-coredump.8.bz2
- ^/usr/share/man/man8/systemd-cryptsetup@.service.8.bz2
- ^/usr/share/man/man8/systemd-cryptsetup-generator.8.bz2
- ^/usr/share/man/man8/systemd-debug-generator.8.bz2
- ^/usr/share/man/man8/systemd-environment-d-generator.8.bz2
- ^/usr/share/man/man8/systemd-fsck@.service.8.bz2
- ^/usr/share/man/man8/systemd-fstab-generator.8.bz2
- ^/usr/share/man/man8/systemd-gpt-auto-generator.8.bz2
- ^/usr/share/man/man8/systemd-getty-generator.8.bz2
- ^/usr/share/man/man8/systemd-halt.service.8.bz2
- ^/usr/share/man/man8/systemd-hibernate-resume-generator.8.bz2
- ^/usr/share/man/man8/systemd-hibernate-resume@.service.8.bz2
- ^/usr/share/man/man8/systemd-hostnamed.service.8.bz2
- ^/usr/share/man/man8/systemd-initctl.service.8.bz2
- ^/usr/share/man/man8/systemd-journald.service.8.bz2
- ^/usr/share/man/man8/systemd-hwdb.8.bz2
- ^/usr/share/man/man8/systemd-localed.service.8.bz2
- ^/usr/share/man/man8/systemd-logind.service.8.bz2
- ^/usr/share/man/man8/systemd-machine-id-commit.service.8.bz2
- ^/usr/share/man/man8/systemd-machined.service.8.bz2
- ^/usr/share/man/man8/systemd-modules-load.service.8.bz2
- ^/usr/share/man/man8/systemd-makefs@.service.8.bz2
- ^/usr/share/man/man8/systemd-networkd-wait-online.service.8.bz2
- ^/usr/share/man/man8/systemd-networkd.service.8.bz2
- ^/usr/share/man/man8/systemd-portabled.service.8.bz2
- ^/usr/share/man/man8/systemd-random-seed.service.8.bz2
- ^/usr/share/man/man8/systemd-quotacheck.service.8.bz2
- ^/usr/share/man/man8/systemd-rc-local-generator.8.bz2
- ^/usr/share/man/man8/systemd-rfkill.service.8.bz2
- ^/usr/share/man/man8/systemd-resolved.service.8.bz2
- ^/usr/share/man/man8/systemd-remount-fs.service.8.bz2
- ^/usr/share/man/man8/systemd-run-generator.8.bz2
- ^/usr/share/man/man8/systemd-sysctl.service.8.bz2
- ^/usr/share/man/man8/systemd-socket-proxyd.8.bz2
- ^/usr/share/man/man8/systemd-suspend.service.8.bz2
- ^/usr/share/man/man8/systemd-system-update-generator.8.bz2
- ^/usr/share/man/man8/systemd-time-wait-sync.service.8.bz2
- ^/usr/share/man/man8/systemd-sysusers.8.bz2
- ^/usr/share/man/man8/systemd-timedated.service.8.bz2
- ^/usr/share/man/man8/systemd-timesyncd.service.8.bz2
- ^/usr/share/man/man8/systemd-update-done.service.8.bz2
- ^/usr/share/man/man8/systemd-tmpfiles.8.bz2
- ^/usr/share/man/man8/systemd-udevd.service.8.bz2
- ^/usr/share/man/man8/systemd-update-utmp.service.8.bz2
- ^/usr/share/man/man8/systemd-user-sessions.service.8.bz2
- ^/usr/share/man/man8/systemd-veritysetup-generator.8.bz2
- ^/usr/share/man/man8/systemd-veritysetup@.service.8.bz2
- ^/usr/share/man/man8/systemd-vconsole-setup.service.8.bz2
- ^/usr/share/man/man8/telinit.8.bz2
- ^/usr/share/man/man8/systemd-volatile-root.service.8.bz2
- ^/usr/share/man/man8/udevadm.8.bz2
- ^/usr/share/man/man3/SD_.*
- ^/usr/share/man/man3/sd_.*
- ^/usr/share/man/man3/udev_.*
- ^/usr/share/man/man3/libudev.3.bz2
- ^/usr/share/systemd/kbd-model-map
- ^/usr/share/systemd/language-fallback-map
- ^/usr/lib/systemd/.*
- ^/usr/lib/pkgconfig/libsystemd.pc
- ^/usr/lib/pkgconfig/libudev.pc
- ^/usr/lib/rpm/macros.d/macros.systemd
- ^/usr/lib/kernel/install.d/00-entry-directory.install
- ^/usr/lib/kernel/install.d/50-depmod.install
- ^/usr/lib/kernel/install.d/90-loaderentry.install
- ^/usr/lib/sysctl.d/50-default.conf
- ^/usr/lib/sysctl.d/50-coredump.conf
- ^/usr/lib/sysusers.d/systemd.conf
- ^/usr/lib/sysusers.d/basic.conf
- ^/usr/lib/tmpfiles.d/etc.conf
- ^/usr/lib/tmpfiles.d/systemd.conf
- ^/usr/lib/tmpfiles.d/var.conf
- ^/usr/lib/tmpfiles.d/home.conf
- ^/usr/lib/tmpfiles.d/journal-nocow.conf
- ^/usr/lib/tmpfiles.d/systemd-nologin.conf
- ^/usr/lib/tmpfiles.d/systemd-nspawn.conf
- ^/usr/lib/tmpfiles.d/portables.conf
- ^/usr/lib/tmpfiles.d/tmp.conf
- ^/usr/lib/tmpfiles.d/x11.conf
- ^/usr/lib/environment.d/99-environment.conf
- ^/usr/bin/kernel-install
- ^/usr/bin/systemd-resolve
- ^/usr/bin/systemd-umount
- ^/usr/bin/systemd-analyze
- ^/usr/bin/systemd-cat
- ^/usr/bin/resolvectl
- ^/usr/bin/bootctl
- ^/usr/bin/systemd-socket-activate
- ^/usr/bin/localectl
- ^/usr/bin/hostnamectl
- ^/usr/bin/timedatectl
- ^/usr/bin/coredumpctl
- ^/usr/bin/systemd.*
- ^/usr/bin/busctl
- ^/usr/bin/systemd-nspawn
- ^/usr/lib64/pkgconfig/libsystemd.pc
- ^/usr/lib64/pkgconfig/libudev.pc
- ^/lib/udev/.*
- ^/lib/libsystemd.so.0
- ^/lib/libsystemd.so
- ^/lib/systemd/.*
- ^/lib/libudev.*
- ^/lib/security/pam_systemd.so
- ^/lib/modprobe.d/systemd.conf
- ^/lib/libnss_myhostname.so.*
- ^/lib/libnss_resolve.so.*
- ^/lib/libnss_systemd.so.*
- ^/lib/libsystemd.so.*
- ^/lib/libnss_mymachines.so.*
- ^/etc/pam.d/systemd-user
- ^/etc/systemd/user/.keep_sys-apps_systemd-0
- ^/etc/systemd/.*
- ^/etc/udev/rules.d/.keep_sys-apps_systemd-0
- ^/etc/udev/udev.conf
- ^/etc/udev/hwdb.d/.keep_sys-apps_systemd-0
- ^/etc/X11/xinit/xinitrc.d/50-systemd-user.sh
- ^/etc/xdg/systemd/user
- ^/etc/sysctl.d/99-sysctl.conf
- ^/etc/binfmt.d/.keep_sys-apps_systemd-0
- ^/etc/modules-load.d/.keep_sys-apps_systemd-0
- ^/etc/tmpfiles.d/.keep_sys-apps_systemd-0
- ^/etc/modprobe.d/blacklist.conf
- ^/bin/systemd-run
- ^/bin/journalctl
- ^/bin/loginctl
- ^/bin/systemd-inhibit
- ^/bin/systemctl
- ^/bin/portablectl
- ^/bin/machinectl
- ^/bin/systemd-firstboot
- ^/bin/systemd-machine-id-setup
- ^/bin/systemd-escape
- ^/bin/systemd-notify
- ^/bin/systemd-ask-password
- ^/bin/systemd-tty-ask-password-agent
- ^/bin/systemd-sysusers
- ^/bin/systemd-hwdb
- ^/bin/systemd-tmpfiles
- ^/bin/udevadm
- ^/bin/networkctl
- ^/var/log/journal/remote/.keep_sys-apps_systemd-0
- ^/var/lib/systemd/.keep_sys-apps_systemd-0
- ^/sbin/init
- ^/sbin/resolvconf
- ^/sbin/halt
- ^/sbin/poweroff
- ^/sbin/reboot
- ^/sbin/runlevel
- ^/sbin/shutdown
- ^/sbin/telinit
- ^/lib64/libsystemd.*
- ^/lib64/libudev.*
- ^/lib64/security/pam_systemd.so
- ^/lib64/libsystemd.*
- ^/lib64/libudev.*
- ^/lib64/libnss_myhostname.*
- ^/lib64/libnss_resolve.*
- ^/lib64/libnss_mymachines.*
- ^/lib64/libnss_systemd.*


# We don't need openrc
- ^/etc/init.d/.*

# GCC split
- ^/etc/env.d/04gcc-x86_64-pc-linux-gnu
- ^/etc/ld.so.conf.d/05gcc-x86_64-pc-linux-gnu.conf
- ^/etc/env.d/gcc.*
- ^/usr/lib/debug/usr/lib/gcc.*
- ^/usr/lib/gcc/x86_64-pc-linux-gnu.*
- ^/usr/share/gcc-data/x86_64-pc-linux-gnu.*
- ^/usr/bin/c\+\+.*
- ^/usr/bin/cc$
- ^/usr/bin/cpp.*
- ^/usr/bin/g\+\+.*
- ^/usr/bin/gcc.*
- ^/usr/bin/gccgo.*
- ^/usr/bin/go-.*
- ^/usr/bin/gofmt-.*
- ^/usr/bin/gcov.*
- ^/usr/bin/gfortran.*
- ^/usr/bin/x86_64-pc-linux-gnu-.*
- ^/usr/lib/gcc/x86_64-pc-linux-gnu.*
- ^/usr/lib/go.*
- ^/usr/lib64/go.*
- ^/usr/libexec/gcc.*
- ^/usr/share/gcc-data.*
- ^/usr/x86_64-pc-linux-gnu/gcc-bin.*
- ^/usr/lib/gcc
- ^/usr/lib/llvm.*
- ^/usr/lib/clang.*
- ^/etc/lvm.*

# devel
- ^/usr/include
