steps:
- emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
- curl https://get.mocaccino.org/luet/get_luet_root.sh | sh
- luet install repository/mocaccino-extra-stable system/luet-extensions
- luet install dev-util/pkgs-checker-minimal utils/jq
- |
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
- LUET_NOLOCK=true
prelude:
- emerge -j ${JOBS} --onlydeps {{ ( index .Values.labels "emerge.packages" ) }}
package_dir: /{{ .Values.name }}
requires:
- name: system-x
  version: '>=0'
  category: layers
