requires:
- category: "layer"
  name: "system-core"
  version: ">=0"
steps:
- cp -rvf package.use/* /etc/portage/package.use/
- cp -rvf package.accept_keywords/* /etc/portage/package.accept_keywords/
- cp -rvf package.license/* /etc/portage/package.license/
