excludes:
- ^/var/cache/distfiles
- ^/var/db/repos
- ^/var/cache/edb
- ^/usr/portage
- ^/var/db/pkg
- ^/var/lib/portage
- ^/var/log
- ^/luetbuild

# Clang-10 devel
- ^/usr/include/.*
- ^/usr/lib/clang/10.0.1/include/.*
- ^/usr/lib/llvm/10/bin
- ^/usr/lib/llvm/10/bin/.*
- ^/usr/lib/llvm/10/include.*
- ^/usr/lib/llvm/10/lib/cmake.*
- ^/usr/lib/llvm/10/libexec.*
env:
- JOBS={{ ( index .Values.labels "emerge.jobs" ) | default "3" }}
- CLANG_10_PKGS="{{ ( index .Values.labels "emerge.packages" ) }}"
steps:
- emerge -j ${JOBS} ${CLANG_10_PKGS}
requires:
- category: "layers"
  name: "system-core"
  version: ">=0"
