steps:
- emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
- curl https://get.mocaccino.org/luet/get_luet_root.sh | sh
- luet install repository/mocaccino-extra-stable system/luet-extensions-live
- luet install dev-util/pkgs-checker-minimal utils/jq
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
- LUET_NOLOCK=true
- LUET_PORTAGE_CACHE_PACKAGES=/var/cache/binpkgs/
- LUET_YES=true
prelude:
- emerge -j ${JOBS} --onlydeps {{ ( index .Values.labels "emerge.packages" ) }}
package_dir: /{{ .Values.name }}
requires:
- name: gnome
  version: '>=0'
  category: layers
- name: libgfbgraph
  version: '>=0.2.2'
  category: net-libs-0.2
- name: libzapojit
  version: '>=0.0.2'
  category: net-libs
