steps:
- emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
- curl https://get.mocaccino.org/luet/get_luet_root.sh | sh
- luet install repository/mocaccino-extra-stable system/luet-extensions
- luet install dev-util/pkgs-checker-minimal utils/jq
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
- LUET_NOLOCK=true
- LUET_PORTAGE_CACHE_PACKAGES=/var/cache/binpkgs/
- LUET_YES=true
prelude:
- emerge -j ${JOBS} --onlydeps {{ ( index .Values.labels "emerge.packages" ) }}
package_dir: /{{ .Values.name }}
requires:
- name: system-x
  version: '>=0'
  category: layers
- name: nodejs
  version: '>=10.19.0'
  category: net-libs
- name: X
  version: '>=0'
  category: layers
- name: unzip
  version: '>=0'
  category: app-arch
- name: plasma
  version: '>=0'
  category: layers
- name: zip
  version: '>=0'
  category: app-arch
- name: expat
  version: '>=0'
  category: dev-libs
- name: cbindgen
  version: '>=0.14.3'
  category: dev-util
