requires:
- category: "development"
  name: "mocaccino-overlay-x"
  version: ">=0"
- category: "layers"
  name: "clang-10"
  version: ">=0"
env:
- FEATURES="-sandbox -usersandbox -ipc-sandbox -pid-sandbox -network-sandbox"
- JOBS=7
prelude:
# TODO: Verify how is handled by luet this use case. ATM, i force remove of the packages rebuild.
- emerge -C app-text/xmlto sys-apps/dbus app-crypt/pinentry sys-apps/systemd
# Ensure that the systemd files and dbus files are removed
- rm -v /usr/lib64/libudev* /lib64/libudev* /usr/lib64/libsystemd* /lib64/libsystem* /lib64/libdbus* /usr/lib/libdbus* /usr/lib64/libdbus*
steps:
- USE=-harfbuzz emerge media-libs/freetype -j $JOBS
- emerge -uDNv --with-bdeps=y --backtrack=100 --autounmask-keep-masks=y @world -j $JOBS
- emerge systemd -j $JOBS

excludes:
- ^/var/db/repos
- ^/var/db/pkg
- ^/var/lib/portage
- ^/var/cache/distfiles
- ^/var/log
- ^/var/cache/edb
- ^/usr/portage
- ^/sys
- ^/proc
- ^/luetbuild

# GCC split
- ^/etc/env.d/04gcc-x86_64-pc-linux-gnu
- ^/etc/ld.so.conf.d/05gcc-x86_64-pc-linux-gnu.conf
- ^/etc/env.d/gcc.*
- ^/usr/lib/debug/usr/lib/gcc.*
- ^/usr/lib/gcc/x86_64-pc-linux-gnu.*
- ^/usr/share/gcc-data/x86_64-pc-linux-gnu.*
- ^/usr/bin/c\+\+.*
- ^/usr/bin/cc$
- ^/usr/bin/cpp.*
- ^/usr/bin/g\+\+.*
- ^/usr/bin/gcc.*
- ^/usr/bin/gccgo.*
- ^/usr/bin/go-.*
- ^/usr/bin/gofmt-.*
- ^/usr/bin/gcov.*
- ^/usr/bin/gfortran.*
- ^/usr/bin/x86_64-pc-linux-gnu-.*
- ^/usr/lib/gcc/x86_64-pc-linux-gnu.*
- ^/usr/lib/go.*
- ^/usr/lib64/go.*
- ^/usr/libexec/gcc.*
- ^/usr/share/gcc-data.*
- ^/usr/x86_64-pc-linux-gnu/gcc-bin.*
- ^/usr/lib/gcc
- ^/usr/lib/llvm.*
- ^/usr/lib/clang.*
- ^/etc/lvm.*

# devel
- ^/usr/include
