requires:
- category: "development"
  name: "mocaccino-overlay-x"
  version: ">=0"
unpack: true
env:
- FEATURES="-sandbox -usersandbox -ipc-sandbox -pid-sandbox"
- JOBS=7
steps:
# we want py3.8 and py2.7 for now
- emerge --unmerge dev-lang/python:3.8
- USE=-harfbuzz emerge media-libs/freetype -j $JOBS
- emerge dev-perl/XML-Parser -j $JOBS
- emerge -uDNv --with-bdeps=y --backtrack=100 --autounmask-keep-masks=y @world -j $JOBS
- emerge sys-apps/systemd
- perl-cleaner --all

excludes:
- ^/etc/shadow
- ^/etc/gshadow
- ^/etc/group
- ^/etc/fstab
- ^/etc/passwd
- ^/etc/machineid
- ^/var/db/repos
- ^/var/db/pkg
- ^/var/lib/portage
- ^/var/cache/distfiles
- ^/var/log
- ^/var/cache/edb
- ^/usr/portage
