includes:
- ^/etc
- ^/etc/env.d
- ^/etc/env.d/gcc
- ^/etc/env.d/gcc/.*
- ^/usr
- ^/usr/lib
- ^/usr/lib/debug
- ^/usr/lib/debug/usr
- ^/usr/lib/debug/usr/lib
- ^/usr/lib/debug/usr/lib/gcc
- ^/usr/lib/debug/usr/lib/gcc/x86_64-pc-linux-gnu
- ^/usr/lib/debug/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}
- ^/usr/lib/debug/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32
- ^/usr/lib/debug/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/crtbegin.o.debug
- ^/usr/lib/debug/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/crtbeginS.o.debug
- ^/usr/lib/debug/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/crtbeginT.o.debug
- ^/usr/lib/debug/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/crtend.o.debug
- ^/usr/lib/debug/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/crtendS.o.debug
- ^/usr/lib/debug/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/crtfastmath.o.debug
- ^/usr/lib/debug/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/crtprec32.o.debug
- ^/usr/lib/debug/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/crtprec64.o.debug
- ^/usr/lib/debug/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/crtprec80.o.debug
- ^/usr/lib/debug/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/libatomic.so.1.2.0.debug
- ^/usr/lib/debug/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/libgcc_s.so.1.debug
- ^/usr/lib/debug/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/libgfortran.so.5.0.0.debug
- ^/usr/lib/debug/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/libgomp.so.1.0.0.debug
- ^/usr/lib/debug/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/libobjc.so.4.0.0.debug
- ^/usr/lib/debug/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/libobjc_gc.so.4.0.0.debug
- ^/usr/lib/debug/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/libquadmath.so.0.0.0.debug
- ^/usr/lib/debug/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/libstdc++.so.6.0.25.debug
- ^/usr/lib/debug/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/vtv_end.o.debug
- ^/usr/lib/debug/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/vtv_end_preinit.o.debug
- ^/usr/lib/debug/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/vtv_start.o.debug
- ^/usr/lib/debug/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/vtv_start_preinit.o.debug
- ^/usr/lib/debug/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/crtbegin.o.debug
- ^/usr/lib/debug/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/crtbeginS.o.debug
- ^/usr/lib/debug/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/crtbeginT.o.debug
- ^/usr/lib/debug/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/crtend.o.debug
- ^/usr/lib/debug/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/crtendS.o.debug
- ^/usr/lib/debug/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/crtfastmath.o.debug
- ^/usr/lib/debug/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/crtprec32.o.debug
- ^/usr/lib/debug/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/crtprec64.o.debug
- ^/usr/lib/debug/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/crtprec80.o.debug
- ^/usr/lib/debug/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/libatomic.so.1.2.0.debug
- ^/usr/lib/debug/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/libgcc_s.so.1.debug
- ^/usr/lib/debug/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/libgfortran.so.5.0.0.debug
- ^/usr/lib/debug/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/libgomp.so.1.0.0.debug
- ^/usr/lib/debug/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/libobjc.so.4.0.0.debug
- ^/usr/lib/debug/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/libobjc_gc.so.4.0.0.debug
- ^/usr/lib/debug/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/libquadmath.so.0.0.0.debug
- ^/usr/lib/debug/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/libstdc++.so.6.0.25.debug
- ^/usr/lib/debug/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/vtv_end.o.debug
- ^/usr/lib/debug/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/vtv_end_preinit.o.debug
- ^/usr/lib/debug/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/vtv_start.o.debug
- ^/usr/lib/debug/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/vtv_start_preinit.o.debug
- ^/usr/lib/gcc
- ^/usr/lib/gcc/x86_64-pc-linux-gnu
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/crtbegin.o
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/crtbeginS.o
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/crtbeginT.o
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/crtend.o
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/crtendS.o
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/crtfastmath.o
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/crtprec32.o
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/crtprec64.o
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/crtprec80.o
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/finclude
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/finclude/ieee_arithmetic.mod
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/finclude/ieee_exceptions.mod
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/finclude/ieee_features.mod
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/libatomic.so
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/libatomic.so.1
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/libatomic.so.1.2.0
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/libgcc_s.so
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/libgcc_s.so.1
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/libgfortran.so
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/libgfortran.so.5
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/libgfortran.so.5.0.0
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/libgomp.so
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/libgomp.so.1
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/libgomp.so.1.0.0
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/libobjc.so
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/libobjc.so.4
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/libobjc.so.4.0.0
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/libobjc_gc.so
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/libobjc_gc.so.4
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/libobjc_gc.so.4.0.0
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/libquadmath.so
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/libquadmath.so.0
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/libquadmath.so.0.0.0
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/libstdc++.so
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/libstdc++.so.6
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/libstdc++.so.6.0.25
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/vtv_end.o
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/vtv_end_preinit.o
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/vtv_start.o
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/32/vtv_start_preinit.o
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/crtbegin.o
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/crtbeginS.o
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/crtbeginT.o
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/crtend.o
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/crtendS.o
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/crtfastmath.o
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/crtprec32.o
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/crtprec64.o
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/crtprec80.o
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/finclude
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/finclude/ieee_arithmetic.mod
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/finclude/ieee_exceptions.mod
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/finclude/ieee_features.mod
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/libatomic.so
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/libatomic.so.1
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/libatomic.so.1.2.0
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/libgcc_s.so
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/libgcc_s.so.1
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/libgfortran.so
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/libgfortran.so.5
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/libgfortran.so.5.0.0
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/libgomp.so
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/libgomp.so.1
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/libgomp.so.1.0.0
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/libobjc.so
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/libobjc.so.4
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/libobjc.so.4.0.0
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/libobjc_gc.so
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/libobjc_gc.so.4
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/libobjc_gc.so.4.0.0
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/libquadmath.so
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/libquadmath.so.0
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/libquadmath.so.0.0.0
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/libstdc++.so
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/libstdc++.so.6
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/libstdc++.so.6.0.25
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/vtv_end.o
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/vtv_end_preinit.o
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/vtv_start.o
- ^/usr/lib/gcc/x86_64-pc-linux-gnu/{{.Values.version}}/vtv_start_preinit.o
- ^/usr/share
- ^/usr/share/gcc-data
- ^/usr/share/gcc-data/x86_64-pc-linux-gnu
- ^/usr/share/gcc-data/x86_64-pc-linux-gnu/{{.Values.version}}
- ^/usr/share/gcc-data/x86_64-pc-linux-gnu/{{.Values.version}}/info
- ^/usr/share/gcc-data/x86_64-pc-linux-gnu/{{.Values.version}}/info/libgomp.info
- ^/usr/share/gcc-data/x86_64-pc-linux-gnu/{{.Values.version}}/info/libquadmath.info
- ^/usr/share/gcc-data/x86_64-pc-linux-gnu/{{.Values.version}}/locale
- ^/usr/share/gcc-data/x86_64-pc-linux-gnu/{{.Values.version}}/locale/de
- ^/usr/share/gcc-data/x86_64-pc-linux-gnu/{{.Values.version}}/locale/de/LC_MESSAGES
- ^/usr/share/gcc-data/x86_64-pc-linux-gnu/{{.Values.version}}/locale/de/LC_MESSAGES/libstdc++.mo
- ^/usr/share/gcc-data/x86_64-pc-linux-gnu/{{.Values.version}}/locale/fr
- ^/usr/share/gcc-data/x86_64-pc-linux-gnu/{{.Values.version}}/locale/fr/LC_MESSAGES
- ^/usr/share/gcc-data/x86_64-pc-linux-gnu/{{.Values.version}}/locale/fr/LC_MESSAGES/libstdc++.mo
unpack: true
requires:
- name: system-x
  version: ">=0"
  category: layers