steps:
- emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
- curl https://get.mocaccino.org/luet/get_luet_root.sh | sh
- luet install repository/mocaccino-extra-stable system/luet-extensions-live
- luet install dev-util/pkgs-checker-minimal utils/jq
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
- LUET_NOLOCK=true
- LUET_PORTAGE_CACHE_PACKAGES=/var/cache/binpkgs/
- LUET_YES=true
prelude:
- emerge -j ${JOBS} --onlydeps {{ ( index .Values.labels "emerge.packages" ) }}
package_dir: /{{ .Values.name }}
requires:
- name: system-x
  version: '>=0'
  category: layers
- name: snappy
  version: '>=0'
  category: app-arch
- name: plasma
  version: '>=0'
  category: layers
- name: X
  version: '>=0'
  category: layers
- name: unzip
  version: '>=0'
  category: app-arch
- name: libxml2
  version: '>=2.9.4-r3'
  category: dev-libs-2
- name: gzip
  version: '>=1.7'
  category: app-arch
- name: gn
  version: '>=0.1807'
  category: dev-util
- name: nodejs
  version: '>=7.6.0'
  category: net-libs
  use_flags:
  - inspector
- name: openh264
  version: '>=1.6.0'
  category: media-libs
- name: re2
  version: '>=0.2019.08.01'
  category: dev-libs
- name: gnome
  version: '>=0'
  category: layers
- name: bzip2
  version: '>=0'
  category: app-arch
- name: expat
  version: '>=0'
  category: dev-libs
