excludes:
- ^/var/db/repos
- ^/var/cache/edb
- ^/usr/portage
- ^/var/db/pkg
- ^/var/lib/portage
- ^/var/log
env:
- JOBS={{ ( index .Values.labels "emerge.jobs" ) | default "3" }}
steps:
- emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }}
requires:
- category: "layers"
  name: "qt"
  version: ">=0"
