unpack: true
requires:
- category: "layers"
  name: "system-x"
  version: ">=0"
excludes:
- ^/sys
- ^/proc
- ^/dev
- ^/var/cache/distfiles
- ^/etc/shadow
- ^/etc/gshadow
- ^/etc/group
- ^/etc/hostname
- ^/etc/hosts
- ^/etc/machine-id
- ^/etc/fstab
- ^/etc/passwd
- ^/etc/machineid
